---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-tester-hpa
  labels:
    app: app-tester
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: app-tester
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
