name: CI - Mobile Automation Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
  
      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar ADB no Ubuntu
        run: sudo apt-get update && sudo apt-get install -y adb

          npm install -g appium
          npm install -g npx
          appium -v

      - name: Configurar Android SDK
        run: |
          echo "Configurando Android SDK..."
          echo "ANDROID_HOME=C:\Users\User\AppData\Local\Android\Sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=C:\Users\User\AppData\Local\Android\Sdk" >> $GITHUB_ENV
          echo "PATH=$PATH;C:\Users\User\AppData\Local\Android\Sdk\platform-tools" >> $GITHUB_ENV
          echo "PATH=$PATH;C:\Users\User\AppData\Local\Android\Sdk\cmdline-tools\latest\bin" >> $GITHUB_ENV

      - name: Criar e Iniciar Emulador Android
        env:
          ANDROID_SDK_ROOT: C:\Users\User\AppData\Local\Android\Sdk
        run: |
          run: |
          echo "Instalando SDK do Android..."
          mkdir -p $ANDROID_SDK_ROOT
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/latest
          export PATH=$ANDROID_SDK_ROOT/latest/bin:$PATH
          yes | sdkmanager --licenses || true
          yes | sdkmanager --install "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

      - name: Criar e Iniciar Emulador Android
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          echo "Criando emulador..."
          export PATH=$ANDROID_SDK_ROOT/latest/bin:$PATH
          echo "no" | avdmanager create avd -n test_avd -k "system-images;android-30;google_apis;x86_64" --device "pixel_4"
    
          echo "Iniciando emulador..."
          nohup emulator -avd test_avd -no-window -no-audio -gpu swiftshader_indirect &
      
          echo "Aguardando inicialização do emulador..."
          adb wait-for-device
          adb shell input keyevent 82
      - name: Aguardar inicialização do Emulador
        run: |
          echo "Esperando emulador iniciar..."
          adb wait-for-device
          adb shell getprop sys.boot_completed

      - name: Instalar APK no Emulador
        run: |
          adb install -r C:/MTGOV_MOBILE/Apps/app.apk

      - name: Iniciar Appium Server
        run: |
          npx appium --log-level error & npx wait-on tcp:4723

      - name: Rodar testes Robot Framework
        run: |
          mkdir logs || true
          robot -d logs ./testCases

      - name: Upload de Relatórios
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Testes
          path: logs/
