name: CI - Mobile Automation Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
  
      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar dependências (ADB e Appium)
        run: |
          choco install adb
          npm install -g appium
          npm install -g npx
          appium -v

      - name: Configurar Android SDK
        run: |
          echo "Configurando Android SDK..."
          echo "ANDROID_HOME=C:\Users\User\AppData\Local\Android\Sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=C:\Users\User\AppData\Local\Android\Sdk" >> $GITHUB_ENV
          echo "PATH=$PATH;C:\Users\User\AppData\Local\Android\Sdk\platform-tools" >> $GITHUB_ENV
          echo "PATH=$PATH;C:\Users\User\AppData\Local\Android\Sdk\cmdline-tools\latest\bin" >> $GITHUB_ENV

      - name: Criar e Iniciar Emulador Android
        run: |
          echo "Criando emulador..."
          echo "no | avdmanager create avd -n test_avd -k 'system-images;android-30;google_apis;x86_64'" | cmd
          echo "Iniciando emulador..."
          emulator -avd test_avd -no-window -no-audio &

      - name: Aguardar inicialização do Emulador
        run: |
          echo "Esperando emulador iniciar..."
          adb wait-for-device
          adb shell getprop sys.boot_completed

      - name: Instalar APK no Emulador
        run: |
          adb install -r C:/MTGOV_MOBILE/Apps/app.apk

      - name: Iniciar Appium Server
        run: |
          npx appium --log-level error & npx wait-on tcp:4723

      - name: Rodar testes Robot Framework
        run: |
          mkdir logs || true
          robot -d logs ./testCases

      - name: Upload de Relatórios
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Testes
          path: logs/
