name: CI - Mobile Automation Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install -r requirements.txt

      - name: Iniciar Appium Server
        run: |
          npm install -g appium
          appium --log appium.log &

      - name: Rodar testes Robot Framework
        run: |
         robot -d logs ./testCases

      - name: Upload de Relatórios
        uses: actions/upload-artifact@v4
        with:
            name: Relatorio-Testes
            path: results/
