name: CI - Mobile Automation Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-automation:
    runs-on: windows-latest

    steps:

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
  
      - name: Install ADB (Windows)
        run: choco install adb
        
      - name: Wait before tests
        run: sleep 20
         
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-appiumlibrary
          pip install -r requirements.txt

      - name: Install dependencies
        run: choco install adb

      - name: Install Android Emulator
        run: |
          # Baixar as ferramentas de linha de comando do Android
          Invoke-WebRequest -Uri "https://dl.google.com/android/repository/commandlinetools-win-7583922_latest.zip" -OutFile "commandlinetools.zip"
          Expand-Archive -Path "commandlinetools.zip" -DestinationPath "C:\android-sdk"

          # Criar o diretório 'latest' necessário para o sdkmanager
          New-Item -Path "C:\android-sdk\cmdline-tools" -Name "latest" -ItemType Directory -Force
          
          # Mover os arquivos extraídos para a pasta 'latest' diretamente
          Move-Item -Path "C:\android-sdk\cmdline-tools\cmdline-tools\*" -Destination "C:\android-sdk\cmdline-tools\latest"

          # Remover a pasta desnecessária após o movimento
          Remove-Item -Path "C:\android-sdk\cmdline-tools\cmdline-tools" -Recurse -Force

          # Configurar o SDK no PATH
          $Env:Path += ";C:\android-sdk\cmdline-tools\latest\bin"

          # Aceitar licenças e instalar os pacotes necessários
          C:\android-sdk\cmdline-tools\latest\bin\sdkmanager --licenses

          # Instalar plataforma e imagens do sistema
          C:\android-sdk\cmdline-tools\latest\bin\sdkmanager "platform-tools" "system-images;android-30;google_apis;x86_64"

      - name: Start Emulator
        run: |
          # Iniciar o emulador Android (não precisa de janela ou áudio)
          Start-Process -NoNewWindow -FilePath "C:\android-sdk\emulator\emulator.exe" -ArgumentList "-avd", "Pixel_4_API_30", "-no-window", "-no-audio"

      - name: Wait for emulator to start
        run: |
          adb wait-for-device

      - name: Install APK
        run: |
          adb install -r C:/MTGOV_MOBILE/Apps/app.apk
      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium --log-level error & npx wait-on tcp:4723

      - name: Rodar testes Robot Framework
        run: |
         robot -d logs ./testCases

      - name: Upload de Relatórios
        uses: actions/upload-artifact@v4
        with:
            name: Relatorio-Testes
            path: results/
